rules:
  property-sort-order:
    - 1
    -
      order:
        - position
        - z-index
        - top
        - right
        - bottom
        - left
        - display
        - visibility
        - float
        - clear
        - clip
        - zoom
        - flex-direction
        - flex-order
        - flex-pack
        - flex-align
        - flex
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - overflow
        - overflow-x
        - overflow-y
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - table-layout
        - empty-cells
        - caption-side
        - border-spacing
        - border-collapse
        - list-style
        - list-style-position
        - list-style-type
        - list-style-image
        - content
        - quotes
        - counter-reset
        - counter-increment
        - resize
        - cursor
        - user-select
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
        - transition
        - transition-delay
        - transition-timing-function
        - transition-duration
        - transition-property
        - transform
        - transform-origin
        - animation
        - animation-name
        - animation-duration
        - animation-play-state
        - animation-timing-function
        - animation-delay
        - animation-iteration-count
        - animation-direction
        - hyphens
        - pointer-events
        - opacity
        - filter:progid:DXImageTransform.Microsoft.Alpha(Opacity
        - border
        - border-width
        - border-style
        - border-color
        - border-top
        - border-top-width
        - border-top-style
        - border-top-color
        - border-right
        - border-right-width
        - border-right-style
        - border-right-color
        - border-bottom
        - border-bottom-width
        - border-bottom-style
        - border-bottom-color
        - border-left
        - border-left-width
        - border-left-style
        - border-left-color
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-right-radius
        - border-bottom-left-radius
        - border-image
        - border-image-source
        - border-image-slice
        - border-image-width
        - border-image-outset
        - border-image-repeat
        - outline
        - outline-width
        - outline-style
        - outline-color
        - outline-offset
        - box-decoration-break
        - box-shadow
        - box-sizing
        - background
        - background-color
        - background-image
        - background-repeat
        - background-attachment
        - background-position
        - background-position-x
        - background-position-y
        - background-clip
        - background-origin
        - background-size
        - font
        - color
        - font-family
        - font-size
        - font-weight
        - font-style
        - font-variant
        - font-size-adjust
        - font-stretch
        - font-effect
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - font-smooth
        - font-icon
        - text-align
        - text-align-last
        - vertical-align
        - white-space
        - text-decoration
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-style
        - text-emphasis-position
        - text-indent
        - text-justify
        - letter-spacing
        - word-spacing
        - text-outline
        - text-transform
        - text-wrap
        - text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - text-shadow
        - word-wrap
        - word-break
        - tab-size
        - line-height
        - filter
      ignore-custom-properties: true
  bem-depth:
    - 0
    - max-depth: 1
  border-zero:
    - 1
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 1
    - filename-extension: true
      leading-underscore: true
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: long
  hex-notation:
    - 1
    - style: uppercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties:
      - font-icon
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes:
    - 1
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-units:
    - 1
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}
  quotes:
    - 1
    - style: single
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
        - 3
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 0
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-for-property:
    - 1
    - properties:
      - color
      - background-color
      - border-color
  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit: 1
